name = "dependency_graph_extractor"
description = "Extract dependency information from Ada projects"
version = "0.1.0"
licenses = "BSD-3-Clause"
website = "https://github.com/TNO/Dependency_Graph_Extractor-Ada"
tags = ["extract", "dependency", "analysis", "graph", "graphml"]

authors = ["Jeroen Ketema", "Pierre van de Laar"]
maintainers = ["Pierre van de Laar <pierre.van.de.laar@gmail.com>"]
maintainers-logins = ["pjljvandelaar"]

[[depends-on]]
libadalang = "^22.0.0"
