name: Ada (GNAT)

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Alire
      uses: alire-project/setup-alire@v1

    - name: Build
      run: cd src && alr build

    - name: Example project to analyze
      run: cd tests/syntax_examples && alr build
